[tool.kedro]
package_name = "perfana_kedro"
project_name = "perfana-kedro"
kedro_init_version = "0.18.5"


[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov perfana_kedro -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.black]
line_length = 120

[tool.isort]
line_length = 120
profile = "black"
known_first_party = ["perfana_kedro"]

[tool.autoflake]
remove_all_unused_imports = true
remove_unused_variables = true
expand_star_imports = true

[tool.mypy]
plugins = "sqlalchemy.ext.mypy.plugin"
ignore_missing_imports = true
exclude = [".venv"]
allow_redefinition = true
