groups:
- name: ./rules.conf
  rules:
  
  - alert: HighLoad
    expr: avg by(system_under_test,test_environment) (system_load_average_1m) > 2
    for: 0s
    labels:
      severity: warning
    annotations:
      description: 'System load average > 2'
      summary: 'System load average > 2'
  - alert: HighGCPauseMaximum
    expr: avg by(system_under_test,test_environment) (jvm_gc_pause_seconds_max) > 100
    for: 0s
    labels:
      severity: warning
    annotations:
      description: 'GC Pause > 100 ms detected'
      summary: 'GC Pause > 100 ms detected'
